### ISSUE TITLE
Restore Backup does not work

### ISSUE THREAD

**Issue by glitch452** [homebridge/docker-homebridge#489]
### Current Situation

I was running home bridge in a VM, and I exported the backup file, then shut down the VM. I started up the container on a Ubuntu 22.04 VM. I tried to restore from backup, but it just hangs when clicking the "restore backup" button. 

![image](https://user-images.githubusercontent.com/894128/212614254-2d8cd5f3-3060-4504-8792-48ed934c22b0.png)

![image](https://user-images.githubusercontent.com/894128/212614413-9cd58465-c3ab-4d30-98ac-6eb2b0b6c29d.png)

### Docker Config

```yml
version: "3"
services:
  homebridge:
    image: oznu/homebridge:latest
    environment:
      TZ: America/Vancouver
      ENABLE_AVAHI: "0"
    volumes:
      - ./config:/homebridge
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "50mb"
        max-file: "7"
```

### Logs

```text
[1/15/2023, 10:23:30 PM] [HB Supervisor] Homebridge Storage Path: /var/lib/homebridge
[1/15/2023, 10:23:30 PM] [HB Supervisor] Homebridge Config Path: /var/lib/homebridge/config.json
[1/15/2023, 10:23:30 PM] [HB Supervisor] Logging to /var/lib/homebridge/homebridge.log
[1/15/2023, 10:23:30 PM] [HB Supervisor] Creating default config.json: /var/lib/homebridge/config.json
[1/15/2023, 10:23:30 PM] [HB Supervisor] OS: Linux 5.15.0-58-generic x64
[1/15/2023, 10:23:30 PM] [HB Supervisor] Node.js v18.13.0 /opt/homebridge/bin/node
[1/15/2023, 10:23:30 PM] [HB Supervisor] Homebridge Path: /var/lib/homebridge/node_modules/homebridge/bin/homebridge
[1/15/2023, 10:23:30 PM] [HB Supervisor] UI Path: /opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[1/15/2023, 10:23:35 PM] [Homebridge UI] Homebridge Config UI X v4.50.2 is listening on :: port 8581
[1/15/2023, 10:23:35 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[1/15/2023, 10:23:35 PM] [HB Supervisor] Started Homebridge v1.6.0 with PID: 150
[1/15/2023, 10:23:36 PM] Loaded config.json with 0 accessories and 1 platforms.
[1/15/2023, 10:23:36 PM] ---
[1/15/2023, 10:23:36 PM] No plugins found.
[1/15/2023, 10:23:36 PM] Loading 1 platforms...
Setup Payload:
X-HM://0023TGAT8QDYF
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ XXX-XX-XXX │     
    └────────────┘     
                       
[1/15/2023, 10:23:36 PM] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge 2E93) is running on port 51933.
```

### Host Operating System

Ubuntu / Debian (or a variant)

### Host Architecture

x86_64 / amd64
