### ISSUE TITLE
 Validation error in Docker Compose file: Additional property 'ersion

### ISSUE THREAD

**Issue by Rfkgaming89** [homebridge/docker-homebridge#512]
### Describe The Bug

Current Situation

Copying the current docker compose file you will get the error

Validation error in Docker Compose file: Additional property 'ersion

 version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1" 

The correct one should be as followed

version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '1'
Removed unnecessary quotation marks around the max-size value. It should be provided as a numeric value without quotes.
Enclosed the value of max-file in quotes to ensure it is treated as a string.

### Docker Config

```yml
 version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1" 
```

### Host Operating System

Ubuntu / Debian (or a variant)

### Host Architecture

x86_64 / amd64
