### ISSUE TITLE
Updating Homebridge UI and Node.js inside container does not persist container restarts

### ISSUE THREAD

**Issue by seanob86** [homebridge/docker-homebridge#519]
### Describe The Bug

In the readme under [Automated Updates](https://github.com/homebridge/docker-homebridge#automated-updates), it states the following:

 `NOTE - The version of Homebridge IS NOT tied to the version of the container. You can update Homebridge, the Homebridge UI and the Node.js runtime from inside the container.`

However tearing down the container and bringing the container back up reverts the updates back to image default. For example the Homebridge UI update to 4.50.5 will not persist after the following
`docker compose down`
`docker compose up -d`
or `docker compose up -d —force-recreate`

From my limited understanding, it seems both UI updates and Node.js updates inside the /opt/homebridge directory but only the /homebridge directory will persist data per the docker compose file.

Therefore it seems that yes you can update inside the container per the README, but with the caveat that data will not persist for Node.js and Homebridge UI updates.

Is this expected?

### Docker Config

```yml
version: '2'
services:
  homebridge:
    image: homebridge/homebridge:latest
    container_name: homebridge
    restart: always
    network_mode: host
    volumes:
      - ./config:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
```

### Host Operating System

Raspberry Pi OS - Latest

### Host Architecture

aarch64 / arm64
