### ISSUE TITLE
Docker Desktop: Host Networking on macOS and Windows.

### ISSUE THREAD

**Issue by cpressland** [homebridge/docker-homebridge#570]
### Current Situation

The wiki states [here](https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Docker) that Windows and macOS are not supported as they lack the `--net=host` parameter. This is no longer the case in Docker Desktop 4.34.0. Homebridge does indeed start and appears to function as expected with one minor issue, the detected IP addresses are that of the docker container itself, and not the host.

### Proposed Change

Allow a configuration variable to force Homebridge to advertise itself on a given IP address even if it's not bound to it, this should allow HomeKit to find the Homeridge instance.

### Additional Context

Docker Desktop documentation: https://docs.docker.com/engine/network/drivers/host/#docker-desktop

**Comment by NorthernMan54** [comment]
Let me test this out, then will update the documentation.

**Comment by gidd-bud** [comment]
Noticed this issue has been re-opened. When will it be fixed? Recently I was having trouble adding HomeBridge to HomeKit.

**Comment by NorthernMan54** [comment]
So I took some time today to look at this closer on my Intel Mac mini, running macOS Monterey.  And while I was able to make some progress, was not able to get homebridge to work.

For the setup, I first enabled host networking in the Docker Desktop

![Screen Shot 2024-12-18 at 10 47 10 AM](https://github.com/user-attachments/assets/1d858c09-45aa-4cac-ae3e-86efb6e84138)

I then used the current docker-compose.yml file for docker-home bridge, and was able to start homebridge.  And was able to access the UI via the url http://docker-desktop.local:8581

I was able to install a couple of plugins without issue, and things appeared to work from the Homebridge UI side of things.

But I was unable to pair Homebridge with the home app on my phone.

And looking deeper, the issue is how Docker handle's local ip addresses on MacOS versus linux.  On linux the docker container uses the same IP address as the host, while on MacOS it uses its own IP address on a different network.

![Screen Shot 2024-12-18 at 11 13 59 AM](https://github.com/user-attachments/assets/7accdeaa-c438-441c-b5ca-e27ef418d2a4)

My host / primary network is 192.168.1.x, and not what you see here.  

What was interesting, was that I could access the homebridge instances and the UI remotely by using the host computers IP address and the proper port number from inside the container.

To get homebridge to work, we would likely need to fool the mDNS Advertiser to think it is working from the host interface, and use its IP address in the advertisements.

**Comment by leecbryant** [comment]
Bumping this feature ask

**Comment by TINKPA** [comment]
It works with docker hosted by [OrbStack](https://docs.orbstack.dev/docker/host-networking) !!!

**Comment by eigenein** [comment]
@TINKPA Could you elaborate how you got it working with OrbStack? For me, the detected IP address is still of the docker container itself

**Comment by PaRkThEcAr** [comment]
> It works with docker hosted by [OrbStack](https://docs.orbstack.dev/docker/host-networking) !!!

Yeah, i am curious on that too. i have an Orbstack install and cant get the MDNS stuff moving the way i want.

```
services:
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
    environment:
      - TZ=America/Denver
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
```
